name: Deploy to AlwaysData

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ssh-${{ secrets.AD_LOGIN }}.alwaysdata.net
          username: ${{ secrets.AD_LOGIN }}
          password: ${{ secrets.AD_PASSWORD }}
          script: |
            cd ~/www
            git pull origin main
            echo "Déploiement terminé"
